[project]
name = "disnake-template"
version = "0.1.0"
description = "Template for my disnake bots"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "disnake>=2.11.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
]
